all_links = [
	"https://rawg.io/games/grand-theft-auto-v",
	"https://rawg.io/games/counter-strike-global-offensive",
	"https://rawg.io/games/left-4-dead-2",
	"https://rawg.io/games/bioshock-infinite",
	"https://rawg.io/games/half-life-2",
	"https://rawg.io/games/god-of-war-2",
	"https://rawg.io/games/doom",
	"https://rawg.io/games/cyberpunk-2077",
	"https://rawg.io/games/grand-theft-auto-iv",
	"https://rawg.io/games/warframe",
	"https://rawg.io/games/metal-gear-solid-v-the-phantom-pain",
	"https://rawg.io/games/the-witcher-2-assassins-of-kings-enhanced-edition",
	"https://rawg.io/games/the-walking-dead",
	"https://rawg.io/games/half-life-2-episode-one",
	"https://rawg.io/games/the-witcher-3-wild-hunt",
	"https://rawg.io/games/tomb-raider",
	"https://rawg.io/games/the-elder-scrolls-v-skyrim",
	"https://rawg.io/games/life-is-strange-episode-1-2",
	"https://rawg.io/games/bioshock",
	"https://rawg.io/games/limbo",
	"https://rawg.io/games/payday-2",
	"https://rawg.io/games/terraria",
	"https://rawg.io/games/dota-2",
	"https://rawg.io/games/metro-2033",
	"https://rawg.io/games/batman-arkham-knight",
	"https://rawg.io/games/the-witcher-enhanced-edition-directors-cut",
	"https://rawg.io/games/apex-legends",
	"https://rawg.io/games/portal-2",
	"https://rawg.io/games/portal",
	"https://rawg.io/games/red-dead-redemption-2",
	"https://rawg.io/games/borderlands-2",
	"https://rawg.io/games/destiny-2",
	"https://rawg.io/games/fallout-4",
	"https://rawg.io/games/team-fortress-2",
	"https://rawg.io/games/horizon-zero-dawn",
	"https://rawg.io/games/rocket-league",
	"https://rawg.io/games/rise-of-the-tomb-raider",
	"https://rawg.io/games/half-life-2-lost-coast",
	"https://rawg.io/games/grand-theft-auto-san-andreas",
	"https://rawg.io/games/shadow-of-mordor",
	"https://rawg.io/games/half-life-2-episode-two",
	"https://rawg.io/games/little-nightmares",
	"https://rawg.io/games/half-life",
	"https://rawg.io/games/outlast",
	"https://rawg.io/games/bioshock-remastered",
	"https://rawg.io/games/spec-ops-the-line",
	"https://rawg.io/games/alan-wake",
	"https://rawg.io/games/saints-row-the-third",
	"https://rawg.io/games/garrys-mod",
	"https://rawg.io/games/fallout-new-vegas",
	"https://rawg.io/games/dishonored-2",
	"https://rawg.io/games/la-noire",
	"https://rawg.io/games/for-honor",
	"https://rawg.io/games/grand-theft-auto-vice-city",
	"https://rawg.io/games/hollow-knight",
	"https://rawg.io/games/hitman",
	"https://rawg.io/games/mirrors-edge",
	"https://rawg.io/games/deus-ex-mankind-divided",
	"https://rawg.io/games/far-cry-3",
	"https://rawg.io/games/amnesia-the-dark-descent",
	"https://rawg.io/games/path-of-exile",
	"https://rawg.io/games/playerunknowns-battlegrounds",
	"https://rawg.io/games/prey",
	"https://rawg.io/games/injustice-gods-among-us-ultimate-edition",
	"https://rawg.io/games/company-of-heroes-2",
	"https://rawg.io/games/super-meat-boy",
	"https://rawg.io/games/hellblade-senuas-sacrifice",
	"https://rawg.io/games/bioshock-2",
	"https://rawg.io/games/dark-souls-iii",
	"https://rawg.io/games/hotline-miami",
	"https://rawg.io/games/half-life-2-deathmatch",
	"https://rawg.io/games/marvels-spider-man",
	"https://rawg.io/games/stardew-valley",
	"https://rawg.io/games/wolfenstein-the-new-order",
	"https://rawg.io/games/detroit-become-human",
	"https://rawg.io/games/borderlands",
	"https://rawg.io/games/the-elder-scrolls-v-skyrim-special-edition",
	"https://rawg.io/games/dishonored",
	"https://rawg.io/games/civilization-v",
	"https://rawg.io/games/half-life-deathmatch-source",
	"https://rawg.io/games/assassins-creed-iv-black-flag",
	"https://rawg.io/games/uncharted-4-a-thiefs-end",
	"https://rawg.io/games/jedi-the-fallen-order",
	"https://rawg.io/games/death-stranding",
	"https://rawg.io/games/borderlands-the-pre-sequel",
	"https://rawg.io/games/counter-strike",
	"https://rawg.io/games/left-4-dead",
	"https://rawg.io/games/fall-guys",
	"https://rawg.io/games/bastion",
	"https://rawg.io/games/monster-hunter-world-2",
	"https://rawg.io/games/resident-evil-7-biohazard",
	"https://rawg.io/games/hades-2018",
	"https://rawg.io/games/titanfall-2",
	"https://rawg.io/games/brutal-legend",
	"https://rawg.io/games/dont-starve-together",
	"https://rawg.io/games/dead-space",
	"https://rawg.io/games/mass-effect-2",
	"https://rawg.io/games/the-last-of-us-remastered",
	"https://rawg.io/games/metal-gear-solid-v-ground-zeroes",
	"https://rawg.io/games/mortal-kombat-x",
	"https://rawg.io/games/metro-redux",
	"https://rawg.io/games/bloodborne",
	"https://rawg.io/games/nierautomata",
	"https://rawg.io/games/journey",
	"https://rawg.io/games/ark-survival-of-the-fittest",
	"https://rawg.io/games/cities-skylines",
	"https://rawg.io/games/batman-arkham-city-goty",
	"https://rawg.io/games/hitman-absolution",
	"https://rawg.io/games/control",
	"https://rawg.io/games/counter-strike-source",
	"https://rawg.io/games/just-cause-3",
	"https://rawg.io/games/metro-last-light-redux",
	"https://rawg.io/games/mass-effect",
	"https://rawg.io/games/bioshock-2-remastered",
	"https://rawg.io/games/just-cause-2",
	"https://rawg.io/games/mad-max",
	"https://rawg.io/games/minecraft",
	"https://rawg.io/games/paladins",
	"https://rawg.io/games/xcom-enemy-unknown",
	"https://rawg.io/games/brothers-a-tale-of-two-sons-2",
	"https://rawg.io/games/nioh-2-the-complete-edition",
	"https://rawg.io/games/armored-core-vi",
	"https://rawg.io/games/synthetik-legion-rising",
	"https://rawg.io/games/talespire",
	"https://rawg.io/games/destiny-2-forsaken-complete-collection",
	"https://rawg.io/games/monster-in-my-pocket",
	"https://rawg.io/games/in-the-hunt-1995",
	"https://rawg.io/games/codename-panzers-phase-two",
	"https://rawg.io/games/cadence-of-hyrule",
	"https://rawg.io/games/dodonpachi-resurrection",
	"https://rawg.io/games/the-isle",
	"https://rawg.io/games/crab-champions",
	"https://rawg.io/games/lego-star-wars-tcs",
	"https://rawg.io/games/left-4-dead-2",
	"https://rawg.io/games/metal-slug",
	"https://rawg.io/games/system-shock-2",
	"https://rawg.io/games/bread-fred",
	"https://rawg.io/games/metal-slug-x",
	"https://rawg.io/games/dying-light-the-following-enhanced-edition",
	"https://rawg.io/games/the-jackbox-party-pack-8",
	"https://rawg.io/games/statik",
	"https://rawg.io/games/tennis-elbow-2013",
	"https://rawg.io/games/mortal-kombat-komplete-edition",
	"https://rawg.io/games/a-way-out-2018",
	"https://rawg.io/games/ghosts-n-goblins-resurrection",
	"https://rawg.io/games/left-4-dead",
	"https://rawg.io/games/xcom-2",
	"https://rawg.io/games/hyper-light-drifter",
	"https://rawg.io/games/handshakes",
	"https://rawg.io/games/sleeping-dogs-definitive-edition",
	"https://rawg.io/games/rayman-origins",
	"https://rawg.io/games/battlefield-bad-company-2",
	"https://rawg.io/games/descent-1996",
	"https://rawg.io/games/rise-of-nations-extended-edition",
	"https://rawg.io/games/n-nplusplus",
	"https://rawg.io/games/baldurs-gate-enhanced-edition",
	"https://rawg.io/games/guild-wars-2",
	"https://rawg.io/games/super-bunny-man",
	"https://rawg.io/games/final-fight-2",
	"https://rawg.io/games/guacamelee-2",
	"https://rawg.io/games/age-of-empires-iii-complete-collection",
	"https://rawg.io/games/sky-light-awaits",
	"https://rawg.io/games/battlefield-bad-company-2-vietnam-2",
	"https://rawg.io/games/ultimate-chicken-horse",
	"https://rawg.io/games/streets-of-rage-4",
	"https://rawg.io/games/gears-of-war-ultimate-edition",
	"https://rawg.io/games/metal-slug-2",
	"https://rawg.io/games/baldurs-gate-dark-alliance-ii",
	"https://rawg.io/games/the-jackbox-party-pack-2",
	"https://rawg.io/games/call-of-duty-black-ops",
	"https://rawg.io/games/serious-sam-the-first-encounter",
	"https://rawg.io/games/river-city-girls",
	"https://rawg.io/games/commandos-beyond-the-call-of-duty",
	"https://rawg.io/games/nuclear-throne",
	"https://rawg.io/games/sackboy-a-big-adventure-2",
	"https://rawg.io/games/warhammer-40000-rogue-trader",
	"https://rawg.io/games/kingdom-two-crowns",
	"https://rawg.io/games/hearts-of-iron-iv",
	"https://rawg.io/games/enter-the-gungeon",
	"https://rawg.io/games/tabletop-simulator",
	"https://rawg.io/games/the-colonists",
	"https://rawg.io/games/until-we-die",
	"https://rawg.io/games/total-war-warhammer",
	"https://rawg.io/games/plateup",
	"https://rawg.io/games/timespinner",
	"https://rawg.io/games/resident-evil-3",
	"https://rawg.io/games/escape-academy",
	"https://rawg.io/games/spec-ops-the-line",
	"https://rawg.io/games/deep-rock-galactic",
	"https://rawg.io/games/wobbly-life",
	"https://rawg.io/games/overcooked",
	"https://rawg.io/games/teenage-mutant-ninja-turtles-shredders-revenge",
	"https://rawg.io/games/wasteland-3",
	"https://rawg.io/games/terraria",
	"https://rawg.io/games/tales-of-symphonia",
	"https://rawg.io/games/dragon-quest-builders-2",
	"https://rawg.io/games/dark-souls-ii",
	"https://rawg.io/games/wilmots-warehouse",
	"https://rawg.io/games/hitman-2",
	"https://rawg.io/games/serious-sam-the-second-encounter",
	"https://rawg.io/games/kingdom-come-deliverance",
	"https://rawg.io/games/dead-cells",
	"https://rawg.io/games/south-park-the-stick-of-truth",
	"https://rawg.io/games/star-wars-knights-of-the-old-republic-2",
	"https://rawg.io/games/half-life-blue-shift",
	"https://rawg.io/games/castle-crashers",
	"https://rawg.io/games/halo-the-master-chief-collection",
	"https://rawg.io/games/dont-starve",
	"https://rawg.io/games/a-plague-tale-innocence",
	"https://rawg.io/games/dead-space-2",
	"https://rawg.io/games/batman-arkham-city-2",
	"https://rawg.io/games/fallout-3",
	"https://rawg.io/games/yakuza-0",
	"https://rawg.io/games/torchlight-ii",
	"https://rawg.io/games/quake-champions",
	"https://rawg.io/games/the-last-of-us",
	"https://rawg.io/games/dragon-age-origins",
	"https://rawg.io/games/subnautica",
	"https://rawg.io/games/divinity-original-sin-2",
	"https://rawg.io/games/chivalry-medieval-warfare",
	"https://rawg.io/games/resident-evil-4",
	"https://rawg.io/games/the-binding-of-isaac",
	"https://rawg.io/games/dmc",
	"https://rawg.io/games/syberia",
	"https://rawg.io/games/dying-light-the-following-enhanced-edition",
	"https://rawg.io/games/guacamelee-super-turbo-championship-edition",
	"https://rawg.io/games/devil-may-cry-5",
	"https://rawg.io/games/call-of-juarez-gunslinger",
	"https://rawg.io/games/dirt-rally",
	"https://rawg.io/games/call-of-duty-black-ops",
	"https://rawg.io/games/assassins-creed-unity-2",
	"https://rawg.io/games/half-life-opposing-force",
	"https://rawg.io/games/fallout-shelter",
	"https://rawg.io/games/darkest-dungeon",
	"https://rawg.io/games/rayman-legends",
	"https://rawg.io/games/the-bureau-xcom-declassified",
	"https://rawg.io/games/quantum-break",
	"https://rawg.io/games/uncharted-3-drakes-deception",
	"https://rawg.io/games/beyond-two-souls",
	"https://rawg.io/games/what-remains-of-edith-finch",
	"https://rawg.io/games/battlefield-4",
	"https://rawg.io/games/goat-simulator",
	"https://rawg.io/games/superhot",
	"https://rawg.io/games/sniper-elite-v2",
	"https://rawg.io/games/ftl-faster-than-light",
	"https://rawg.io/games/hotline-miami-2-wrong-number",
	"https://rawg.io/games/kingdom-classic",
	"https://rawg.io/games/deus-ex-human-revolution",
	"https://rawg.io/games/surviving-mars",
	"https://rawg.io/games/postal-2",
	"https://rawg.io/games/a-story-about-my-uncle",
	"https://rawg.io/games/to-the-moon",
	"https://rawg.io/games/euro-truck-simulator-2",
	"https://rawg.io/games/cod-black-ops-ii",
	"https://rawg.io/games/mafia-iii",
	"https://rawg.io/games/call-of-duty-wwii",
	"https://rawg.io/games/homefront",
	"https://rawg.io/games/the-witness",
	"https://rawg.io/games/resident-evil-2",
	"https://rawg.io/games/call-of-duty-modern-warfare-3",
	"https://rawg.io/games/the-walking-dead-season-2",
	"https://rawg.io/games/sleeping-dogs",
	"https://rawg.io/games/infamous-second-son",
	"https://rawg.io/games/forza-horizon-4",
	"https://rawg.io/games/alan-wakes-american-nightmare",
	"https://rawg.io/games/bayonetta",
	"https://rawg.io/games/payday-the-heist",
	"https://rawg.io/games/sleeping-dogs-definitive-edition",
	"https://rawg.io/games/grim-fandango-remastered",
	"https://rawg.io/games/days-gone",
	"https://rawg.io/games/broforce",
	"https://rawg.io/games/dragon-age-inquisition",
	"https://rawg.io/games/resident-evil-6",
	"https://rawg.io/games/ratchet-clank",
	"https://rawg.io/games/ori-and-the-will-of-the-wisps",
	"https://rawg.io/games/tom-clancys-the-division",
	"https://rawg.io/games/the-outer-worlds",
	"https://rawg.io/games/the-sims-4",
	"https://rawg.io/games/syberia-2",
	"https://rawg.io/games/the-legend-of-zelda-breath-of-the-wild",
	"https://rawg.io/games/smite",
	"https://rawg.io/games/warhammer-40000-space-marine",
	"https://rawg.io/games/age-of-wonders-iii",
	"https://rawg.io/games/batman-arkham-asylum",
	"https://rawg.io/games/borderlands-3",
	"https://rawg.io/games/metal-gear-rising-revengeance",
	"https://rawg.io/games/deus-ex-game-of-the-year-edition",
	"https://rawg.io/games/mafia-the-city-of-lost-heaven",
	"https://rawg.io/games/frostpunk",
	"https://rawg.io/games/hitman-blood-money",
	"https://rawg.io/games/oddworld-abes-oddysee",
	"https://rawg.io/games/lego-lord-of-the-rings",
	"https://rawg.io/games/the-binding-of-isaac-rebirth",
	"https://rawg.io/games/darksiders-ii-deathinitive-edition",
	"https://rawg.io/games/dark-souls-ii-scholar-of-the-first-sin",
	"https://rawg.io/games/borderlands-game-of-the-year-enhanced",
	"https://rawg.io/games/until-dawn",
	"https://rawg.io/games/star-wars-battlefront-2",
	"https://rawg.io/games/the-forest",
	"https://rawg.io/games/half-life-source",
	"https://rawg.io/games/celeste",
	"https://rawg.io/games/dead-by-daylight",
	"https://rawg.io/games/human-fall-flat",
	"https://rawg.io/games/rust",
	"https://rawg.io/games/the-long-dark",
	"https://rawg.io/games/titan-souls",
	"https://rawg.io/games/wolfenstein-the-old-blood",
	"https://rawg.io/games/team-fortress-classic",
	"https://rawg.io/games/overcooked",
	"https://rawg.io/games/final-fantasy-xv",
	"https://rawg.io/games/wallpaper-engine",
	"https://rawg.io/games/assassins-creed-syndicate-2",
	"https://rawg.io/games/black-mesa",
	"https://rawg.io/games/dark-souls-prepare-to-die-edition",
	"https://rawg.io/games/company-of-heroes",
	"https://rawg.io/games/ghost-of-tsushima",
	"https://rawg.io/games/a-way-out-2018",
	"https://rawg.io/games/stalker-shadow-of-chernobyl",
	"https://rawg.io/games/doki-doki-literature-club",
	"https://rawg.io/games/guns-of-icarus-online",
	"https://rawg.io/games/tropico-4",
	"https://rawg.io/games/max-payne",
	"https://rawg.io/games/divinity-original-sin-enhanced-edition",
	"https://rawg.io/games/sid-meiers-civilization-iii-complete",
	"https://rawg.io/games/jotun",
	"https://rawg.io/games/braid",
	"https://rawg.io/games/minion-masters",
	"https://rawg.io/games/beholder",
	"https://rawg.io/games/resident-evil",
	"https://rawg.io/games/trine-enchanted-edition",
	"https://rawg.io/games/neverwinter",
	"https://rawg.io/games/mark-of-the-ninja",
	"https://rawg.io/games/endless-space-emperor-edition",
	"https://rawg.io/games/fear",
	"https://rawg.io/games/ryse-son-of-rome",
	"https://rawg.io/games/mortal-kombat-11",
	"https://rawg.io/games/the-evil-within",
	"https://rawg.io/games/kotor-ii",
	"https://rawg.io/games/counter-strike-condition-zero-deleted-scenes",
	"https://rawg.io/games/murdered-soul-suspect",
	"https://rawg.io/games/dark-souls8482-remastered",
	"https://rawg.io/games/serious-sam-fusion-2017-beta",
	"https://rawg.io/games/darksiders-ii",
	"https://rawg.io/games/fallout-2-a-post-nuclear-role-playing-game",
	"https://rawg.io/games/game-of-thrones-a-telltale-games-series",
	"https://rawg.io/games/fornite-battle-royale",
	"https://rawg.io/games/resident-evil-2-2019",
	"https://rawg.io/games/dear-esther-landmark-edition",
	"https://rawg.io/games/hacknet",
	"https://rawg.io/games/grid",
	"https://rawg.io/games/prison-architect-all-day-and-a-psych",
	"https://rawg.io/games/sea-of-thieves",
	"https://rawg.io/games/red-orchestra-2-heroes-of-stalingrad-with-rising-s",
	"https://rawg.io/games/sanctum-2",
	"https://rawg.io/games/assassins-creed",
	"https://rawg.io/games/starbound",
	"https://rawg.io/games/lords-of-the-fallen",
	"https://rawg.io/games/the-playroom",
	"https://rawg.io/games/enter-the-gungeon",
	"https://rawg.io/games/far-cry-3-blood-dragon-2",
	"https://rawg.io/games/jet-set-radio-2012",
	"https://rawg.io/games/re-revelations-2",
	"https://rawg.io/games/destiny",
	"https://rawg.io/games/orwell",
	"https://rawg.io/games/fallout-3-game-of-the-year-edition",
	"https://rawg.io/games/remember-me",
	"https://rawg.io/games/tales-from-the-borderlands",
	"https://rawg.io/games/star-wars-battlefront",
	"https://rawg.io/games/resident-evil-3",
	"https://rawg.io/games/mafia-ii-definitive-edition",
	"https://rawg.io/games/the-flame-in-the-flood",
	"https://rawg.io/games/dying-light",
	"https://rawg.io/games/battlefield-3",
	"https://rawg.io/games/the-talos-principle",
	"https://rawg.io/games/serious-sam-3-bfe",
	"https://rawg.io/games/the-elder-scrolls-online-tamriel-unlimited",
	"https://rawg.io/games/battleblock-theater",
	"https://rawg.io/games/lego-the-hobbit",
	"https://rawg.io/games/broken-age",
	"https://rawg.io/games/abzu-2",
	"https://rawg.io/games/far-cry-2-fortunes-edition",
	"https://rawg.io/games/monaco-whats-yours-is-mine",
	"https://rawg.io/games/planetside-2",
	"https://rawg.io/games/lara-croft-gol",
	"https://rawg.io/games/slay-the-spire",
	"https://rawg.io/games/drawful-2",
	"https://rawg.io/games/gwent-the-witcher-card-game",
	"https://rawg.io/games/killing-floor-2",
	"https://rawg.io/games/final-fantasy-vii-remake",
	"https://rawg.io/games/assassins-creed-brotherhood-2",
	"https://rawg.io/games/child-of-light",
	"https://rawg.io/games/stray-2",
	"https://rawg.io/games/oxenfree",
	"https://rawg.io/games/sonic-mania",
	"https://rawg.io/games/dragons-dogma-dark-arisen",
	"https://rawg.io/games/fear-3",
	"https://rawg.io/games/stellaris",
	"https://rawg.io/games/fear-2-project-origin",
	"https://rawg.io/games/rogue-legacy",
	"https://rawg.io/games/vampyr",
	"https://rawg.io/games/killer-is-dead-nightmare-edition",
	"https://rawg.io/games/deponia",
	"https://rawg.io/games/deep-rock-galactic",
	"https://rawg.io/games/persona-5",
	"https://rawg.io/games/vrchat",
	"https://rawg.io/games/divinity-original-sin",
	"https://rawg.io/games/valiant-hearts-the-great-war",
	"https://rawg.io/games/gris",
	"https://rawg.io/games/assassins-creed-revelations",
	"https://rawg.io/games/day-of-defeat-source",
	"https://rawg.io/games/vampire-survivors",
	"https://rawg.io/games/mafia",
	"https://rawg.io/games/binary-domain",
	"https://rawg.io/games/yakuza-kiwami",
	"https://rawg.io/games/morrowind",
	"https://rawg.io/games/dust-an-elysian-tail",
	"https://rawg.io/games/heroes-generals",
	"https://rawg.io/games/burnout-paradise-the-ultimate-box",
	"https://rawg.io/games/battlefield-v",
	"https://rawg.io/games/spelunky",
	"https://rawg.io/games/star-wars-battlefront-ii-2",
	"https://rawg.io/games/gothic-playable-teaser",
	"https://rawg.io/games/resident-evil-village",
	"https://rawg.io/games/the-swapper",
	"https://rawg.io/games/sniper-elite-4",
	"https://rawg.io/games/max-payne-2-the-fall-of-max-payne",
	"https://rawg.io/games/tabletop-simulator",
	"https://rawg.io/games/overlord",
	"https://rawg.io/games/crysis-2-maximum-edition",
	"https://rawg.io/games/it-takes-two-2",
	"https://rawg.io/games/uncharted-legacy-of-thieves-collection",
	"https://rawg.io/games/dirt-showdown",
	"https://rawg.io/games/crash-bandicoot-n-sane-trilogy",
	"https://rawg.io/games/medal-of-honor",
	"https://rawg.io/games/shadow-of-the-colossus",
	"https://rawg.io/games/tomb-raider-underworld",
	"https://rawg.io/games/pillars-of-eternity",
	"https://rawg.io/games/red-faction-guerrilla",
	"https://rawg.io/games/call-of-duty-modern-warfare-remastered",
	"https://rawg.io/games/machinarium",
	"https://rawg.io/games/the-lego-ninjago-movie-video-game",
	"https://rawg.io/games/sins-of-a-solar-empire-rebellion",
	"https://rawg.io/games/outer-wilds",
	"https://rawg.io/games/the-elder-scrolls-iv-oblivion-game-of-the-year-edi",
	"https://rawg.io/games/the-awesome-adventures-of-capitan-spirit",
	"https://rawg.io/games/gears-5",
	"https://rawg.io/games/stalker-call-of-pripyat",
	"https://rawg.io/games/stalker-clear-sky",
	"https://rawg.io/games/street-fighter-v",
	"https://rawg.io/games/torchlight",
	"https://rawg.io/games/sunset-overdrive",
	"https://rawg.io/games/guardians-of-the-galaxy",
	"https://rawg.io/games/outlast-2",
	"https://rawg.io/games/robocraft",
	"https://rawg.io/games/crysis",
	"https://rawg.io/games/mass-effect-3",
	"https://rawg.io/games/rage",
	"https://rawg.io/games/hitman-2-silent-assassin",
	"https://rawg.io/games/magicka-2",
	"https://rawg.io/games/injustice-2",
	"https://rawg.io/games/day-of-defeat",
	"https://rawg.io/games/shadow-warrior-classic-redux",
	"https://rawg.io/games/life-is-strange-before-storm",
	"https://rawg.io/games/alien-swarm",
	"https://rawg.io/games/gone-home",
	"https://rawg.io/games/deathmatch-classic",
	"https://rawg.io/games/metro-last-light",
	"https://rawg.io/games/life-is-strange-2",
	"https://rawg.io/games/valheim",
	"https://rawg.io/games/forza-horizon-5",
	"https://rawg.io/games/world-of-goo",
	"https://rawg.io/games/call-of-duty-world-at-war",
	"https://rawg.io/games/shadow-tactics",
	"https://rawg.io/games/deponia-the-complete-journey",
	"https://rawg.io/games/satellite-reign",
	"https://rawg.io/games/red-faction-armageddon",
	"https://rawg.io/games/ricochet",
	"https://rawg.io/games/deathloop-2",
	"https://rawg.io/games/bully-scholarship-edition",
	"https://rawg.io/games/system-shock-2",
	"https://rawg.io/games/never-alone",
	"https://rawg.io/games/resident-evil-revelations-biohazard-revelations",
	"https://rawg.io/games/arma-cold-war-assault",
	"https://rawg.io/games/sonic-generations",
	"https://rawg.io/games/assassins-creed-valhalla",
	"https://rawg.io/games/tomb-raider-legend",
	"https://rawg.io/games/battlefield-bad-company-2",
	"https://rawg.io/games/hell-yeah-wrath-of-the-dead-rabbit",
	"https://rawg.io/games/ghostrunner",
	"https://rawg.io/games/deus-ex-2-invisible-war",
	"https://rawg.io/games/galactic-civilizations-ii-ultimate-edition",
	"https://rawg.io/games/steep",
	"https://rawg.io/games/stories-the-path-of-destinies",
	"https://rawg.io/games/totally-accurate-battlegrounds",
	"https://rawg.io/games/awesomenauts",
	"https://rawg.io/games/star-wars-jedi-knight-jedi-academy",
	"https://rawg.io/games/orcs-must-die-2",
	"https://rawg.io/games/god-of-war-iii-remastered",
	"https://rawg.io/games/deadlight",
	"https://rawg.io/games/spyro-reignited-trilogy",
	"https://rawg.io/games/kholat",
	"https://rawg.io/games/uncharted-the-lost-legacy",
	"https://rawg.io/games/clicker-heroes",
	"https://rawg.io/games/overcooked-2",
	"https://rawg.io/games/tomb-raider-anniversary",
	"https://rawg.io/games/tell-me-why",
	"https://rawg.io/games/evolve-stage-2",
	"https://rawg.io/games/shadowrun-dragonfall-dc",
	"https://rawg.io/games/trove",
	"https://rawg.io/games/the-evil-within-2",
	"https://rawg.io/games/modern-warfare",
	"https://rawg.io/games/final-fantasy-vii",
	"https://rawg.io/games/battlerite",
	"https://rawg.io/games/outland",
	"https://rawg.io/games/katana-zero",
	"https://rawg.io/games/dota-underlords",
	"https://rawg.io/games/everlasting-summer",
	"https://rawg.io/games/marvels-spider-man-miles-morales",
	"https://rawg.io/games/tekken-7",
	"https://rawg.io/games/renegade-ops",
]

studios = [
"Nordic Games Publishing",
"Bluehole",
"Codemasters",
"Hothead Games",
"Osauhing Creative Mobile",
"SCS Software",
"SEGA",
"Parables Games",
"Motion Twin",
"Daybreak Game Company",
"Koch Media",
"Xbox Game Studios",
"Runic Games",
"Mossmouth",
"2D BOY",
"Mojang",
"Atmospheric",
"Rockstar Games",
"Final Fight 3",
"Daedalic Entertainment",
"GSC World Publishing",
"Team Cherry",
"Nicalis",
"BlitWorks",
"Alawar Entertainment",
"Activision Value Publishing",
"Microsoft Studios",
"Includes Source SDK",
"The Playroom VR",
"stats",
"Starbreeze",
"Harebrained Holdings",
"Online PvP",
"Microids",
"Gathering of Developers",
"exclusive",
"Alawar Premium",
"SUPERHOT Team",
"Valve",
"Kalypso Media",
"Facepalm Games",
"Edmund McMillen",
"Final Fight",
"Crytek",
"NVIDIA",
"Dark",
"THQ Nordic",
"X.D. Network",
"Playdigious",
"Activison",
"Frozenbyte",
"Fellow Traveller",
"Amanita Design",
"Adult Swim Games",
"Astro's Playroom",
"Disney Interactive",
"Klei Entertainment",
"Feral Interactive",
"FromSoftware",
"Lunar Ray Games",
"PSN",
"PvP",
"Paradox Interactive",
"Team Salvato",
"Frictional Games",
"505 Games",
"Singleplayer",
"First-Person",
"Starbreeze Studios",
"BANDAI NAMCO Entertainment US",
"Sierra Online",
"SoftBank",
"8-4",
"GT Interactive Software",
"Behaviour Interactive",
"Spearhead Games",
"Chucklefish",
"Running With Scissors",
"Psychological",
"Microsoft Game Studios",
"Team17 Digital",
"SCE",
"Number None",
"Freebird Games",
"Muse Games",
"Vivendi Universal Games",
"Ronimo Games",
"Stardock Entertainment",
"Coffee Stain Studios",
"Re-Logic",
"Nintendo Australia",
"Heart Machine",
"Harebrained Schemes",
"Thriller",
"Curve Digital",
"Telltale Games",
"Multiple Endings",
"DrinkBox Studios",
"Abylight",
"ak tronic Software & Services",
"Multiplayer",
"Metanet Software",
"Surprise Attack",
"Facepunch Studios",
"Action-Adventure",
"Night School",
"2K Games",
"Mastertronic Group",
"Gamera Games",
"Double Eleven",
"Infogrames",
"FISHLABS",
"PlayStation Mobile",
"Final Fight: Double Impact",
"Sierra Entertainment",
"Deep Silver",
"Capcom",
"0+ Everyone",
"10+ Everyone 10+",
"IMGN.PRO",
"Hinterland Studio",
"Take Two Interactive",
"Steam Cloud",
"MacSoft",
"PlayStation",
"Robot Entertainment",
"Housemarque",
"13+ Teen",
"Digital Extremes",
"Techland Publishing",
"Larian Studios",
"Thunder Lotus Games",
"Iceberg Interactive",
"Beamdog",
"Supergiant Games",
"Cellar Door Games",
"Warner Bros. Interactive",
"17+ Mature",
"Overhaul Games",
"Crowbar Collective",
"Mega Crit Games",
"Double Fine Productions",
"SUPERHOT",
"Subset Games",
"3D Realms",
"THQ",
"1C-SoftClub",
"KRAFTON",
"Night School Studio",
"Missing Link Games",
"Imagination",
"Aspyr",
"Devolver Digital",
"Atari",
"Triumph Studios",
"Activision Blizzard",
"Quantic Dream",
"Private Division",
"ConcernedApe",
"1980s",
"Psyonix",
"Rebellion",
"The Molasses Flood",
"CI Games",
"Annapurna Interactive",
"Co-op",
"Horror",
"GHI Media",
"Full controller support",
"Warhorse Studios",
"Techland",
"Red Ant Enterprises",
"Bethesda Softworks",
"Supernatural",
"true exclusive",
"Steam Leaderboards",
"5 Lives Studios",
"Focus Home Interactive",
"Night School Studios",
"CD PROJEKT RED",
"LAN Co-op",
"Steam Achievements",
"Square Enix",
"Playdead",
"Io-Interactive",
"Nightdive Studios",
"Reverb Communications",
"E-Line Media",
"Active",
"The Behemoth",
"Bungie",
"Humble Hearts",
"Eidos Interactive",
"1C Company",
"JoWooD Entertainment",
"Spike Chunsoft",
"Sierra On-Line",
"Square",
"Mode 7",
"GSC Game World",
"DotEmu",
"The Adventure Company",
"Survival Horror",
"Headup Games",
"Thekla",
"Matt Makes Games",
"Interplay Productions",
"Tripwire Interactive",
"Raw Fury",
"Perfect World Entertainment",
"Red Barrels",
"Atlus",
"Electronic Arts",
"inXile Entertainment",
"LAN PvP",
"Stylized",
"Sony Computer Entertainment",
"11 bit studios",
"Perfect World",
"Psychedelic",
"Oddworld Inhabitants",
"Hi-Rez Studios",
"Majesco Entertainment",
"Pocketwatch Games",
"CyberFront",
"Anuman Interactive",
"Croteam",
"Grinding Gear Games",
"Koei Tecmo Games",
"Gearbox Publishing",
"Introversion Software",
"Creative Mobile",
"Ubisoft Entertainment",
"Buka Entertainment",
"Nintendo",
"Skybound Games",
"Torn Banner Studios",
"LucasArts Entertainment",
"Bandai Namco Entertainment",
"Red Hook Studios",
"Plug In Digital",
" Not rated",
"Sony Interactive Entertainment",
"BANDAI NAMCO Entertainment Europe",
"Demons",
"Trion Worlds",
"Humble Bundle",
"DTP Entertainment",
"Akella",
"Konami",
"Tomorrow",
"Ninja Theory",
"Online Co-Op",
"Unknown Worlds Entertainment",
"thatgamecompany",
"RP Rating Pending",
"Jackbox Games",
"collectathon",
"Remedy Entertainment",
"The Fullbright Company",
]


